name: Erik Windahl Olsen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6277807604055852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3efec'
    - '#121013'
    - '#fdd02f'
    - '#474a57'
    - '#afa6a7'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
