name: Erik Windahl Olsen
favicon: null
layout_spectrum: 0.1185717168264091
typography_spectrum: 0.6277807604055852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffefc'
    - '#101010'
    - '#97aebe'
    - '#595951'
    - '#b18172'
  brandStrength: 0.5
  lightness: 0.3153672812040895
  saturation: 0.5652075749821961
  rhythmicContrast: 0.002246398711577058
purpose: []
